---

- name: "configuration play." 
  hosts: localhost
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 500 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 500

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - configure-server

    