apiVersion: v1
kind: Service
metadata:  
  name: localhostf
  namespace: jumia-frontend
spec:
  selector:    
    app: frontend-label
  type: NodePort
  ports:  
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30035
    protocol: TCP


